//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationSystem.Web.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReservationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReservationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReservationSystem.Web.Resource.ReservationResource", typeof(ReservationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckIn date &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string ErrorCheckIn {
            get {
                return ResourceManager.GetString("ErrorCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckIn date &apos;{0}&apos; should not be greater than Checkout date &apos;{1}&apos;.
        /// </summary>
        internal static string ErrorCheckInCheckOut {
            get {
                return ResourceManager.GetString("ErrorCheckInCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckIn date is not valid..
        /// </summary>
        internal static string ErrorCheckInInput {
            get {
                return ResourceManager.GetString("ErrorCheckInInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckIn date &apos;{0}&apos; should not be less than today&apos;s date.
        /// </summary>
        internal static string ErrorCheckInOld {
            get {
                return ResourceManager.GetString("ErrorCheckInOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckOut date &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string ErrorCheckOut {
            get {
                return ResourceManager.GetString("ErrorCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckOut date is not valid..
        /// </summary>
        internal static string ErrorCheckOutInput {
            get {
                return ResourceManager.GetString("ErrorCheckOutInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string ErrorLocation {
            get {
                return ResourceManager.GetString("ErrorLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location field is required..
        /// </summary>
        internal static string ErrorLocationNull {
            get {
                return ResourceManager.GetString("ErrorLocationNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select number of room to reserve..
        /// </summary>
        internal static string ErrorRoomNumber {
            get {
                return ResourceManager.GetString("ErrorRoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occured, please contact your system admin.
        /// </summary>
        internal static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation successful in location &apos;{0}&apos;.
        /// </summary>
        internal static string SuccessReservation {
            get {
                return ResourceManager.GetString("SuccessReservation", resourceCulture);
            }
        }
    }
}
